# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'demo' do
  
  #pod 'SnapKit' swift
  pod 'Masonry'
  pod 'YogaKit'
  #pod 'AsyncDisplayKit'
end
